- type: guideEntry
  id: Security
  name: гід-вхід-безпека
  text: "/ServerInfo/Guidebook/Security/Security.xml"
  children:
  - Forensics
  - Defusal
  - CriminalRecords
#  - SpaceLaw # TODO

- type: guideEntry
  id: Forensics
  name: гід-вхід-криміналістика
  text: "/ServerInfo/Guidebook/Security/Forensics.xml"

- type: guideEntry
  id: Defusal
  name: гід-вхід-знешкодження
  text: "/ServerInfo/Guidebook/Security/Defusal.xml"

- type: guideEntry
  id: CriminalRecords
  name: довідник-вписка-судимість
  text: "/ServerInfo/Guidebook/Security/CriminalRecords.xml"

# Begin DeltaV Removals - wizden, wrong
#- type: guideEntry
#  id: SpaceLaw
#  name: guide-entry-rules-space-law
#  text: "/ServerInfo/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml"
#  children:
#  - SpaceLawCrimeList

#- type: guideEntry
#  id: SpaceLawCrimeList
#  name: guide-entry-rules-sl-crime-list
#  text: "/ServerInfo/Guidebook/ServerRules/SpaceLaw/SLCrimeList.xml"
# End DeltaV Removals
