- type: guideEntry
  id: Service
  name: гід-вхід-сервіс
  text: "/ServerInfo/Guidebook/Service/Service.xml"
  filterEnabled: True
  children:
  - Bartender
  - Botany
  - Chef
  - Janitorial
  
- type: guideEntry
  id: Bartender
  name: гід-вхід-бармен
  text: "/ServerInfo/Guidebook/Service/Bartender.xml"
  filterEnabled: True

- type: guideEntry
  id: Botany
  name: путівник-вхід-ботаніка
  text: "/ServerInfo/Guidebook/Service/Botany.xml"

- type: guideEntry
  id: Chef
  name: гід-вхід-кухар
  text: "/ServerInfo/Guidebook/Service/Chef.xml"

- type: guideEntry
  id: Janitorial
  name: гід-вхід-двірник
  text: "/ServerInfo/Guidebook/Service/Janitorial.xml"
