- type: startingGear
  id: RadioGuardGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack
    shoes: ClothingShoesBootsLaceup
    id: SyndiListeningPostPDA
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorPlateCarrierUnremoveable

- type: entity
  categories: [ HideSpawnMenu ]
  parent: ClothingOuterArmorPlateCarrier
  id: ClothingOuterArmorPlateCarrierUnremoveable
  name: щеплена пластинка-носій
  suffix: Незнімний
  description: Стандартний носій пластин, який був жорстоко прищеплений до тіла свого власника
  components:
  - type: Unremoveable
