# you can RE any cloning board you find to unlock all 3
- type: entity
  abstract: true
  id: BaseCloningBoard
  components:
  - type: ReverseEngineering
    difficulty: 3
    recipes:
    - CloningConsoleComputerCircuitboard
    - CloningPodMachineCircuitboard
    - MedicalScannerMachineCircuitboard

- type: entity
  id: ReverseEngineeringMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: зворотне проектування машина машина плата
  description: Машинна друкована плата для машини зворотного проектування
  components:
  - type: Sprite
    state: engineering
  - type: MachineBoard
    prototype: ReverseEngineeringMachine
    stackRequirements:
      Cable: 1
      PlasmaGlass: 5
      Manipulator: 2
    tagRequirements:
      BorgArm:
        amount: 3
        defaultPrototype: LeftArmBorg
  # TODO: make this reverse engineerable to the upgraded one

- type: entity
  id: DeepFryerMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: плата машини для фритюрниці
  components:
  - type: Sprite
    state: service
  - type: MachineBoard
    prototype: KitchenDeepFryer
    stackRequirements:
      Steel: 4
      Glass: 2
      Cable: 4
      Manipulator: 2

- type: entity
  id: MailTeleporterMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: плата машини телепорту пошти
  components:
  - type: Sprite
    state: supply
  - type: MachineBoard
    prototype: MailTeleporter
    stackRequirements:
      Steel: 4
      Cable: 4
      Manipulator: 2
