- type: entity
  name: ящик для наручників
  parent: BoxCardboard
  id: BoxHandcuff
  description: Ящик, повний наручників.
  components:
  - type: Storage
    whitelist:
      components:
      - Handcuff
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: Handcuffs
        amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: handcuff

- type: entity
  name: коробка на блискавці
  parent: BoxCardboard
  id: BoxZiptie
  description: Коробка, повна блискавок.
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: Zipties
        amount: 9
  - type: Sprite
    layers:
    - state: box_security
    - state: ziptie

- type: entity
  name: коробка flashbang
  parent: BoxCardboard
  id: BoxFlashbang
  description: 'ПОПЕРЕДЖЕННЯ: Ці пристрої надзвичайно небезпечні та можуть спричинити сліпоту або глухоту при повторному використанні.
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: GrenadeFlashBang
        amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: flashbang

- type: entity
  name: жало під гранату
  parent: BoxCardboard
  id: BoxStinger
  description: Ящик, повний жальних гранат. Розійтися!
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: GrenadeStinger
        amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: flashbang

- type: entity
  name: ящик для гранати зі сльозогінним газом
  parent: BoxCardboard
  id: BoxTearGas
  description: Ящик, повний гранат зі сльозогінним газом. Затримайте подих.
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: TearGasGrenade
        amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: flashbang

- type: entity
  name: sechud box
  parent: BoxCardboard
  id: BoxSechud
  description: Коробка сечуд.
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: ClothingEyesHudSecurity
        amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: sechud
      sprite: _DV/Objects/Storage/boxes.rsi # DeltaV

- type: entity
  name: ящик для секційних окулярів
  parent: BoxCardboard
  id: BoxSecglasses
  description: Коробка захисних окулярів.
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: ClothingEyesGlassesSecurity
        amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: secglasses
      sprite: _DV/Objects/Storage/boxes.rsi # DeltaV

- type: entity
  name: коробка для сонцезахисних окулярів
  parent: BoxCardboard
  id: BoxSunglasses
  description: Коробка крутих спалахостійких сонцезахисних окулярів.
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: ClothingEyesGlassesSunglasses
        amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: sunglasses

- type: entity
  name: коробка для криміналістичного блокнота
  parent: BoxCardboard
  id: BoxForensicPad
  description: Коробка криміналістичних блокнотів.
  components:
  - type: Item
    shape:
    - 0,0,1,1
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: ForensicPad
        amount: 9
  - type: Sprite
    layers:
    - state: box_security
    - state: forensic

- type: entity
  parent: BoxCardboard
  id: BoxDetonator
  name: коробка-детонатор
  description: loadout-group-vox-tank
  components:
  - type: Item
    shape:
    - 0,0,1,1
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: EmptyDetonator
          amount: 3
        - id: TimerTrigger
          amount: 2
        - id: VoiceTrigger
  - type: Sprite
    layers:
    - state: box_security
    - state: trigger
