- type: quickPhrase
  id: BaseSecuritySubjectPhrase
  parent: [ BaseSubjectPhrase, BaseSecurityPhrase ]
  abstract: true

- type: quickPhrase
  id: HandcuffsPhrase
  parent: BaseSecuritySubjectPhrase
  text: фрази-кайданки

- type: quickPhrase
  id: StunBatonPhrase
  parent: BaseSecuritySubjectPhrase
  text: фраза-апк

- type: quickPhrase
  id: DisablerPhrase
  parent: BaseSecuritySubjectPhrase
  text: засіб відключення фрази

- type: quickPhrase
  id: FlashPhrase
  parent: BaseSecuritySubjectPhrase
  text: фраза-спалах

- type: quickPhrase
  id: FlashbangPhrase
  parent: BaseSecuritySubjectPhrase
  text: фраза-спалах

- type: quickPhrase
  id: ArrestPhrase
  parent: BaseSecuritySubjectPhrase
  text: фраза-арешт

- type: quickPhrase
  id: WarrantPhrase
  parent: BaseSecuritySubjectPhrase
  text: фраза-ордер

- type: quickPhrase
  id: wantedPhrase
  parent: BaseSecuritySubjectPhrase
  text: фраза-хотів

- type: quickPhrase
  id: SearchPhrase
  parent: BaseSecuritySubjectPhrase
  text: фразовий пошук

- type: quickPhrase
  id: DetainPhrase
  parent: BaseSecuritySubjectPhrase
  text: фраза-затримати

- type: quickPhrase
  id: SuspectPhrase
  parent: BaseSecuritySubjectPhrase
  text: фраза-підозр

- type: quickPhrase
  id: ForensicScannerPhrase
  parent: BaseSecuritySubjectPhrase
  text: станція-маяк-прокурор

- type: quickPhrase
  id: ForensicPadPhrase
  parent: BaseSecuritySubjectPhrase
  text: фрази-криміналістики

- type: quickPhrase
  id: LogProbePhrase
  parent: BaseSecuritySubjectPhrase
  text: фраза-доступ

- type: quickPhrase
  id: ReleasePhrase
  parent: BaseSecuritySubjectPhrase
  text: фраза-відпуск

- type: quickPhrase
  id: ParolePhrase
  parent: BaseSecuritySubjectPhrase
  text: фраза-звинувачення
