- type: quickPhrase
  id: BaseServiceSubjectPhrase
  parent: [ BaseSubjectPhrase, BaseServicePhrase ]
  abstract: true

- type: quickPhrase
  id: MeatPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-м'ясо

- type: quickPhrase
  id: FlourPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-мука

- type: quickPhrase
  id: RicePhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-рис

- type: quickPhrase
  id: DoughPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-тісто

- type: quickPhrase
  id: BreadPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-хліб

- type: quickPhrase
  id: MilkPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-розташування-верф

- type: quickPhrase
  id: EggPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-яйце

- type: quickPhrase
  id: WheatPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-пшениця

- type: quickPhrase
  id: VegetablePhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-овоч

- type: quickPhrase
  id: FruitPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-плід

- type: quickPhrase
  id: SugarPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-цукор

- type: quickPhrase
  id: AlcoholPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-алкоголь

- type: quickPhrase
  id: NonAlcoholicPhrase
  parent: BaseServiceSubjectPhrase
  text: фразеолог

- type: quickPhrase
  id: JuicePhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-сок

- type: quickPhrase
  id: MopPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-швабра

- type: quickPhrase
  id: BucketPhrase
  parent: BaseServiceSubjectPhrase
  text: фразеологізм

- type: quickPhrase
  id: SpaceCleanerPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-простір-очисник

- type: quickPhrase
  id: SoapPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-мило

- type: quickPhrase
  id: TrashPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-треш

- type: quickPhrase
  id: StagePhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-етап

- type: quickPhrase
  id: SeedPhrase
  parent: BaseServiceSubjectPhrase
  text: словосполучення-сем

- type: quickPhrase
  id: PlantPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-рослина

- type: quickPhrase
  id: MutagenPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-мутаген

- type: quickPhrase
  id: RobustPhrase
  parent: BaseServiceSubjectPhrase
  text: фразеологічний

- type: quickPhrase
  id: WeedPhrase
  parent: BaseServiceSubjectPhrase
  text: словосполучення-бур'ян

- type: quickPhrase
  id: KnifePhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-ніж

- type: quickPhrase
  id: MicrowavePhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-мікрохвильовка

- type: quickPhrase
  id: GrillPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-гриль

- type: quickPhrase
  id: SweetPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-солодкий

- type: quickPhrase
  id: SourPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-кислий

- type: quickPhrase
  id: SpicyPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-пряний

- type: quickPhrase
  id: SavoryPhrase
  parent: BaseServiceSubjectPhrase
  text: фразеологізм

- type: quickPhrase
  id: BitterPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-гірка

- type: quickPhrase
  id: TomatoPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-помідор

- type: quickPhrase
  id: PotatoPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-картопля

- type: quickPhrase
  id: OnionPhrase
  parent: BaseServiceSubjectPhrase
  text: словосполучення-цибуля

- type: quickPhrase
  id: AloePhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-алое

- type: quickPhrase
  id: PoppyPhrase
  parent: BaseServiceSubjectPhrase
  text: фраза-мак

- type: quickPhrase
  id: GalaxyThistlePhrase
  parent: BaseServiceSubjectPhrase
  text: фразеологізм
