- type: entity
  parent: LockerJanitor
  id: HydraLocker
  name: шафка для запуску cleanade
  description: Для прибиральника на місії ця шафка містить пускову установку Hydra та 2 коробки патронів Cleanade.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: WeaponLauncherHydra
        - id: CleanadeGrenadeBox
          amount: 2

- type: entity
  parent: CratePlastic
  id: CleanadeGrenadeCrate
  name: ящик для чистої гранати
  description: Ящик чистих гранат. Містить 2 ящики чистих гранат для пускової установки Hydra.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: CleanadeGrenadeBox
        amount: 2
