# gloves
- type: entity
  parent: BaseAction
  id: ActionToggleKnuckleDustersStun
  name: Перемкнути оглушаючі кулаки пилу
  description: Перемикає вбудовану електрошокову палицю.
  components:
  - type: InstantAction
    event: !type:ToggleActionEvent
