- type: entity
  parent: BoxCardboard
  id: BoxTapeRecorder
  name: коробка магнітофона
  description: Коробка з різнокольоровими касетами та магнітофоном.
  components:
  - type: Sprite
    layers:
    - state: box_security
    - sprite: _DV/Objects/Storage/boxes.rsi
      state: recorder
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: CassetteTape
          amount: 4
        - id: TapeRecorder

- type: entity
  parent: BoxCardboard
  id: BoxMindshield
  name: коробка розумового щита
  description: Коробка, наповнена імплантатами щита розуму.
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: MindShieldImplanter
        amount: 4

- type: entity
  parent: BoxCardboard
  id: BoxC4
  name: коробка c4
  description: Ящик, наповнений C4.
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: C4
        amount: 4
