- type: job
  id: Passenger
  name: job-name-passenger # DeltaV – це використовується скрізь для резервних варіантів, тому я не хотів це змінювати, але зараз написано Assistant
  description: job-description-assistant # DeltaV - Passenger to Assistant
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  access:
  - Maintenance

- type: startingGear
  id: PassengerGear
  equipment:
    #id: PassengerPDA # DeltaV: different PDAs in loadouts
    ears: ClothingHeadsetGrey
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: PassengerChameleonOutfit
  job: Passenger
  equipment:
    head: ClothingHeadHatWelding
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckMantle
    outerClothing: ClothingOuterWinterCoat
    gloves: ClothingHandsGlovesColorYellowBudget
