- type: job
  id: Visitor
  name: job-name-visiter
  description: посадовий опис відвідувача
  playTimeTracker: JobVisitor
  canBeAntag: false
  icon: JobIconVisitor
  setPreference: false
  overrideConsoleVisibility: true
  access:
  - Maintenance
  extendedAccess:
  - External
