- type: entity
  parent: CrateSecgear
  id: CrateSecurityArmor
  name: броньовий ящик
  description: Містить три бронежилети. Щоб відкрити, потрібен безпековий доступ.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: ClothingOuterArmorPlateCarrier # DeltaV - ClothingOuterArmorBulletproof replaced in favour of plate carrier
        amount: 3

- type: entity
  parent: CrateSecgear
  id: CrateSecurityHelmet
  name: ящик для шолома
  description: Містить три стандартні відра мозку. Щоб відкрити, потрібен безпековий доступ.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: ClothingHeadHelmetBasic
        amount: 3

- type: entity
  parent: CrateSecgear
  id: CrateSecurityNonlethal
  name: нелетальний ящик
  description: Містить суміш засобів для знешкодження, електрошокових палиць і спалахів. Щоб відкрити, потрібен безпековий доступ.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: WeaponDisabler
          amount: 3
        - id: Stunbaton
          amount: 3
        - id: BoxFlashbang
        - id: Flash
          amount: 3
#        - Pepperspray
#        - GrenadeTeargas

- type: entity
  parent: CrateSecgear
  id: CrateSecuritySupplies
  name: ящик для забезпечення безпеки
  description: Містить різні припаси для служби безпеки станції. Щоб відкрити, потрібен безпековий доступ.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxHandcuff
        - id: BoxSechud
#        - SecBelt
#        - SecGasmask
#        - SpacelawBook

- type: entity
  parent: CrateSecgear
  id: CrateRestraints
  name: обмежувальний ящик
  description: Містить дві коробки з наручниками та застібками. Щоб відкрити, потрібен безпековий доступ.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxHandcuff
          amount: 2
        - id: BoxZiptie
          amount: 2

- type: entity
  parent: CrateSecgear
  id: CrateSecurityBiosuit
  name: ящик для біокостюмів безпеки
  description: Містить 2 костюми біологічної небезпеки, щоб жодна хвороба не відволікала вас від ваших обов'язків. Щоб відкрити, потрібен безпековий доступ.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: FillBiohazardGearSecurity
          rolls: 2
        - id: ClothingMaskSterile
          amount: 2

- type: entity
  parent: CrateSecgear
  id: CrateSecurityTrackingMindshieldImplants
  name: ящик імплантатора
  description: Містить 4 імпланти MindShield і 4 імплантати для стеження. Щоб відкрити, потрібен безпековий доступ.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: MindShieldImplanter
          amount: 4
        - id: TrackingImplanter
          amount: 4

- type: entity
  parent: CrateSecgear
  id: CrateSecNonlethalThrowables
  name: нелетальний ящик для метання
  description: Містить по одній коробці з флешбенгами, стингерами, гранатами зі сльозогінним газом і чотирма бола. Щоб відкрити, потрібен безпековий доступ.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxFlashbang
        - id: BoxStinger
        - id: BoxTearGas
        - id: Bola # replace with 4 e-bolas when added
          amount: 4
