- type: entity
  parent: CratePlastic
  id: CrateServiceJanitorialSupplies
  name: ящик для прибирального приладдя
  description: Боріться з брудом і брудом за допомогою Nanotrasen Janitorial Essentials(tm)! Містить три відра, попереджувальні знаки та очищувальні гранати. Також є одна швабра, мітла, спрей для чищення, дротяна щітка, ганчірка та пакет для сміття.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: AllSoapsTable
        - id: MopItem
        - id: MopBucketCubeWrapped
        - id: Bucket
          amount: 3
        - id: WetFloorSign
          amount: 2
        - id: SprayBottleSpaceCleaner
          amount: 2
        - id: TrashBag
          amount: 2
        - id: Plunger
          amount: 2
        - id: BoxCleanerGrenades
        - id: WireBrush
          amount: 2

- type: entity
  parent: CratePlastic
  id: CrateServiceCleanerGrenades
  name: об'ємний ящик для очищення
  description: Містить дві коробки очищувальних гранат для тих глибоко вкорінених плям.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: BoxCleanerGrenades
        amount: 2

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceReplacementLights
  name: ящик для заміни світильників
  description: Нехай світло ефіру осяє цю станцію! Або, принаймні, світло дванадцяти люмінесцентних ламп і дванадцяти лампочок розжарювання.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxLighttube
        - id: BoxLightbulb

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceColorfulLights
  name: ящик з різнокольоровими вогнями
  description: Це не вечірка, поки її погано видно, трохи дезорієнтуєш і не болять вуха. Містить дванадцять світлових трубок і дванадцять лампочок різних кольорів.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxLightbulbColorfulMixed
        - id: BoxLighttubeColorfulMixed

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceHolidayLights
  name: ящик для святкових вогнів
  description: Прикрасьте зали цими святковими вогнями! Містить дванадцять червоних і дванадцять зелених світлових трубок.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: BoxLighttubeHoliday
        amount: 2

- type: entity
  parent: CrateGenericSteel
  id: CrateMousetrapBoxes
  name: ящик для мишоловок
  description: Мишоловки, коли всю службу переслідує ціла орда щурів. Використовуйте економно... чи ні.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: BoxMousetrap

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceSmokeables
  name: ящик для паління
  description: Втомилися від швидкої смерті на вокзалі? Замовляйте цей ящик і куріть дорогу до кашлю!
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:GroupSelector
          children:
          - id: CigCartonGreen
            weight: 0.33 # DeltaV
          - id: CigCartonRed
        - !type:GroupSelector
          children:
          - id: CigCartonBlue
            weight: 0.33 # DeltaV
          - id: CigCartonBlack
        # Begin DeltaV additions -Extra Cigs
        - !type:GroupSelector
          children:
          - id: CigCartonPurple
            weight: 0.33
          - id: CigCartonCandy
        # End DeltaV additions -Extra Cigs
        - !type:GroupSelector
          children:
          - id: CigarGoldCase
            weight: 0.05
          - id: CigarCase
        - id: Matchbox
          amount: 2

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceTheatre
  name: театральні вистави ящик
  description: Містить плащ від молі, перукарські ножиці, уніформу покоївки, атрибути клоуна та пантоміми та інші принади.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BarberScissors
        - id: ClothingOuterSuitMonkey
        - id: ClothingHeadHatAnimalMonkey
        - id: ClothingUniformJumpskirtJanimaid
        - id: ClothingUniformJumpskirtOldDress
        - id: ClothingHeadHatMagician
        - !type:AllSelector # Cloaks
          children:
          - id: ClothingNeckCloakMoth
          - id: ClothingNeckCloakVoid
        - !type:AllSelector # Clown starter kit
          children:
          - id: ClothingMaskClown
          - id: ClownRecorder
          - !type:GroupSelector
            children:
            - id: ClothingShoesClown
            - id: ClothingShoesClownLarge
              weight: 0.1
          - !type:NestedSelector
            tableId: RandomBikeHornTable
        - !type:AllSelector # Mime starter kit
          children:
          - id: ClothingMaskMime
          - id: ClothingBeltSuspendersRed
          - id: ClothingBeltSuspendersBlack
        - !type:AllSelector # Performer starter kit
          children:
          - id: ClothingUniformJumpskirtPerformer
          - id: ClothingShoesBootsPerformer
          - id: ClothingHeadPerformerWig

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceCustomSmokable
  name: Ящик для паління своїми руками
  description: Хочете підійти трохи творчо до того, чим ви руйнуєте свої легені? Тоді цей ящик для вас! Є все необхідне для самостійного скручування сигарет.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: PackPaperRolling
        - id: CigaretteFilter
          amount: 8
        - id: GroundTobacco
          amount: 4
        - id: SmokingPipe
        - id: Matchbox

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceBureaucracy
  name: бюрократичний ящик
  description: Кілька стосів паперу, кілька ручок і офісна іграшка. Що ще можна побажати?
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        # DeltaV - replace the paper in the bureaucracy crate with a ream
        - id: BoxReamWhite
        #- id: Paper
        #  amount: 12
        #- id: PaperOffice
        #  amount: 6
        - id: Pen
          amount: 2
        - id: BoxFolderClipboardEmpty
          amount: 2
        - id: HandLabeler
        - id: BoxFolderBlueEmpty
          amount: 2 # DeltaV - more folders in the bureacracy crate
        - id: BoxFolderRedEmpty
          amount: 2 # DeltaV - more folders in the bureacracy crate
        - id: BoxFolderYellowEmpty
          amount: 2 # DeltaV - more folders in the bureacracy crate
        # Begin DeltaV: sticky notes
        - id: PaperStickyNoteStackFilled
        - id: PaperStickyNoteStackFilledPink
        - id: PaperStickyNoteStackFilledGreen
        - id: PaperStickyNoteStackFilledBlue
        # End DeltaV: sticky notes
        - id: NewtonCradle
        - id: BoxEnvelope
        - id: BrbSign
        # Begin DeltaV - More folders & colored paper reams in the bureaucracy crate + denied/approved stamp, low chance of paperwork hater stamp
        - id: BoxFolderBlack
          amount: 2
        - id: BoxFolderGrey
          amount: 2
        - id: BoxFolderGreen
          amount: 2
        - id: BoxReamClassic
        - id: BoxReamBright
        - id: RubberStampHatePaperwork
          prob: 0.05
        - id: RubberStampApproved
        - id: RubberStampDenied
        # End DeltaV - More folders & colored paper reams in the bureaucracy crate + denied/approved stamp, low chance of paperwork hater stamp

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceFaxMachine
  name: ящик факсу
  description: Факс і викрутка для встановлення імені.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: Screwdriver
        - id: FaxMachineFlatpack

- type: entity
  parent: CrateCommandSecure
  id: CrateServicePersonnel
  name: кадровий ящик
  description: Містить коробку з чистими ідентифікаційними картками та КПК.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxPDA
        - id: BoxID

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceBooks
  name: ящик для книг
  description: Містить 10 порожніх книг випадкового вигляду.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: BookRandom
        amount: 10

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceGuidebooks
  name: ящик з путівниками
  description: Містить путівники.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BookSpaceEncyclopedia
        - id: BookTheBookOfControl
        - id: BookBartendersManual
        - id: BookHowToCookForFortySpaceman
        - id: BookLeafLoversSecret
        - id: BookEngineersHandbook
        - id: BookScientistsGuidebook
        - id: BookSecurity
        - id: BookHowToKeepStationClean
        - id: BookHowToRockAndStone
        - id: BookMedicalReferenceBook
        - id: BookHowToSurvive
        - id: BookChemicalCompendium
        - id: BookSpaceLaw

- type: entity
  parent: CrateFreezer
  id: CrateServiceSodaDispenser
  name: ящик для заправки дозатора газованої води
  description: Містить заправки для дозаторів газованої води.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: DrinkCoffeeJug
        - id: DrinkColaBottleFull
        - id: DrinkCreamCartonXL
        - id: DrinkDrGibbJug
        - id: DrinkEnergyDrinkJug
        - id: DrinkGreenTeaJug
        - id: DrinkIceJug
        - id: DrinkJuiceLimeCartonXL
        - id: DrinkJuiceOrangeCartonXL
        - id: DrinkLemonLimeJug
        - id: DrinkRootBeerJug
        - id: DrinkSodaWaterBottleFull
        - id: DrinkSpaceMountainWindBottleFull
        - id: DrinkSpaceUpBottleFull
        - id: DrinkSugarJug
        - id: DrinkTeaJug
        - id: DrinkTonicWaterBottleFull
        - id: DrinkWaterMelonJuiceJug

- type: entity
  parent: CrateFreezer
  id: CrateServiceBoozeDispenser
  name: Коробка з кількома випадково підібраними інструментами, відібраними найкращими музикантами Centcomm!
  description: Містить заправки для дозаторів випивки.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: DrinkAleBottleFullGrowler
        - id: DrinkBeerGrowler
        - id: DrinkCoffeeLiqueurBottleFull
        - id: DrinkCognacBottleFull
        - id: DrinkGinBottleFull
        - id: DrinkMeadJug
        - id: DrinkRumBottleFull
        - id: DrinkTequilaBottleFull
        - id: DrinkVermouthBottleFull
        - id: DrinkVodkaBottleFull
        - id: DrinkWhiskeyBottleFull
        - id: DrinkWineBottleFull
        - id: DrinkJaegermisterBottleFull # Den - Jaegerminster

- type: entity
  parent: CratePlastic
  id: CrateServiceBox
  name: ящики ящик
  description: Містить 6 порожніх багатоцільових коробок.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: BoxCardboard
        amount: 6

- type: entity
  parent: CratePlastic
  id: CrateJanitorBiosuit
  name: двірник біо костюм ящик
  description: Містить 2 костюми біологічної небезпеки, щоб жодна хвороба не відволікала вас від прибирання.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: FillBiohazardGearJanitor
          rolls: 2
        - id: ClothingMaskSterile
          amount: 2

- type: entity
  parent: CrateTrashCart
  id: CrateTrashCartFilled
  suffix: Заповнений
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
          # Creatures
        - id: MobCockroach
          prob: 0.05
        - id: MobMothroach
          prob: 0.03
        - id: MobRosyMothroach # Frontier
          prob: 0.005 # Frontier
        - id: MobMouse
          prob: 0.05
          # Food Packaging
        - id: FoodPacketBoritosTrash
          prob: 0.1
        - id: FoodPacketCheesieTrash
          prob: 0.1
        - id: FoodPacketChipsTrash
          prob: 0.1
        - id: FoodPacketSusTrash
          prob: 0.1
        - id: FoodPacketSyndiTrash
          prob: 0.1
        - id: FoodPacketChowMeinTrash
          prob: 0.1
        - id: FoodPacketDanDanTrash
          prob: 0.1
        - id: FoodPacketMRETrash
          prob: 0.1
        - id: FoodPacketPistachioTrash
          prob: 0.1
        - id: FoodPacketSemkiTrash
          prob: 0.1
        - id: FoodPacketRaisinsTrash
          prob: 0.1
          # Cans
        - id: FoodTinBeansTrash
          prob: 0.15
        - id: FoodTinPeachesTrash
          prob: 0.15
        - id: FoodTinMRETrash
          prob: 0.15
          # Cigarette Stuff
        - id: Ash
          prob: 0.15
        - id: CigaretteSpent
          prob: 0.15
          # Bacteria
        - id: FoodBreadMoldySlice
          prob: 0.15
        - id: FoodPizzaMoldySlice
          prob: 0.15
          # Botanical Waste
        - id: TrashBananaPeel
          prob: 0.15
        - id: FoodCornTrash
          prob: 0.15
          # Misc
        - id: DrinkGlass
          prob: 0.15
        - id: BrokenBottle
          prob: 0.15
        - id: LightTubeBroken
          prob: 0.15
        - id: LightBulbBroken
          prob: 0.15
        - id: MobMouseDead
          prob: 0.1
        - id: Syringe
          prob: 0.1
        - id: ShardGlassPlasma
          prob: 0.1

- type: entity
  parent: CrateGenericSteel
  id: CrateCandles
  name: ящик для свічок
  description: Містить 4 коробки свічок, 2 великі та 2 маленькі. Для атмосфери чи що.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxCandle
          amount: 2
        - id: BoxCandleSmall
          amount: 2
