# Ensure that all setPreference are set to false here. Otherwise, they appear on the job select screen.
# These are for ghost role play timers anyways

- type: job
  id: RoleLaika
  name: амплуа-лайка
  description: роль-опис-лайка
  setPreference: false
  canBeAntag: false
  playTimeTracker: RoleLaika
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 4h

- type: job
  id: RoleShiva
  name: роль-ім'я-шива
  description: роль-опис-шива
  setPreference: false
  canBeAntag: false
  playTimeTracker: RoleShiva
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 4h

- type: job
  id: RoleSilvia
  name: роль-ім'я-сільвія
  description: роль-опис-сільвія
  setPreference: false
  canBeAntag: false
  playTimeTracker: RoleSilvia
  requirements:
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 4h

- type: job
  id: RoleIfrit
  name: роль-ім'я-іфріт
  description: роль-опис-іфрит
  setPreference: false
  canBeAntag: false
  playTimeTracker: RoleIfrit
  requirements:
  - !type:DepartmentTimeRequirement
    department: Epistemics
    time: 4h
  - !type:OverallPlaytimeRequirement
    time: 48h

- type: job
  id: RoleCarpy
  name: роль-ім'я-карпі
  description: роль-опис-карпи
  setPreference: false
  canBeAntag: false
  playTimeTracker: RoleCarpy
  requirements:
  - !type:DepartmentTimeRequirement
    department: Justice
    time: 1h

- type: job
  id: RolePunPun
  name: роль-ім'я-каламбур
  description: Seek to become the most feared person on the station. Змусьте їх відсахнутися при згадці вашого імені!
  setPreference: false
  playTimeTracker: RolePunPun
  requirements:
  - !type:RoleTimeRequirement
    role: JobBartender
    time: 1h

- type: job
  id: RoleBaba
  name: роль-ім'я-баба
  description: фраза-розташування-півн
  setPreference: false
  playTimeTracker: RoleBaba
  requirements:
  - !type:RoleTimeRequirement
    role: JobBartender
    time: 1h
